# Generated by Django 4.0.3 on 2022-04-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]
    operations = [
        migrations.AddField(
            model_name='students',
            name='sem',
            field=models.TextField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
