# Generated by Django 4.0.3 on 2022-04-05 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_presentabsent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentabsent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 12, 45, 54, 286536)),
        ),
    ]
