# Generated by Django 4.0.3 on 2022-04-06 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_presentabsent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentabsent',
            name='name',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presentabsent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 11, 44, 15, 351314)),
        ),
    ]
