# Generated by Django 4.0.3 on 2022-04-08 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_presentabsent_name_alter_presentabsent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentabsent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 23, 35, 8, 502056)),
        ),
    ]
