# Generated by Django 4.0.3 on 2022-04-09 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_presentabsent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='branch',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presentabsent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 21, 45, 20, 912294)),
        ),
    ]
